### PR TITLE
feat(i18n): translation key format

### PR DESCRIPTION
**Pull request by mjkeaton**
## 📝 Description

Relates to #105.

Changes the format of i18n keys from:
```
t('pages.contact.button.text') // => "Save"
```
to
```
t('Save') // => "Save"
```

If there is need for context, e.g. "Save" can be translated differently in other languages and is needed on multiple views, a prefix can always be introduced, e.g. `contact:Save` or similar.

---

## ✅ Checklist

Please ensure the following tasks are completed before requesting a review:

- [x] My code adheres to the style guidelines of this project.
- [x] I have run `npm run lint` or the equivalent linting command.
- [x] I have checked that there are no console errors or warnings.
- [x] I have verified that the application builds without errors.

---

## 🚀 Changes Made

- **New Features:**
  - translation keys now use plain sentences

## 🤝 Related Issues

List any related issues, pull requests, or discussions:

- #105

### CODE REVIEW

**Comment by mjkeaton** [comment]
@cryptosalomao Please take a look. Suggestion is coming from @HubertusVIE. Do you approve of the changes?

**Comment by HubertusVIE** [comment]
> If there is need for context, e.g. "Save" can be translated differently in other languages and is needed on multiple views, a prefix can always be introduced, e.g. contact:Save or similar.

We can also make the Figma labels more explicit, e.g. "Save contact". The short labels are intentional though, it makes the app look less wordy and simpler.

**Comment by mjkeaton** [comment]
> > If there is need for context, e.g. "Save" can be translated differently in other languages and is needed on multiple views, a prefix can always be introduced, e.g. contact:Save or similar.
> 
> We can also make the Figma labels more explicit, e.g. "Save contact". The short labels are intentional though, it makes the app look less wordy and simpler.

Less wordy and focus on simple language is preferable. It's more about avoiding ambiguities or misunderstandings. But we will figure this out once translation starts and can add improve the small subset of keys that are affected.
What do you say @HubertusVIE, should this new format be tried, i.e. this PR merged?

**Review by HubertusVIE — APPROVED** [review]
As discussed with Mykyta

**Comment by HubertusVIE** [comment]
Need a quick intro as soon as I can do something.

**Comment by HubertusVIE** [comment]
Let's schedule a CrowdIn handover session for a running start: https://calendly.com/hjh-bellevue/30min

**Pull request merged**
