### PR TITLE
Date selection component

### PR DESCRIPTION
**Pull request by matosGu1lherme**
## 📝 Description

This pull request introduces the creation of the date selection component, which opens a date picker when accessed. It allows users to select either a single date or a date range with predefined periods.

Relates to #31 

---

## 📸 Screenshots/Screen record (if applicable)

[Gravação de tela de 29-11-2024 19:49:00.webm](https://github.com/user-attachments/assets/dc1f84a5-ab34-46b4-bd2c-416fcbfe0166)

---

## ✅ Checklist

Please ensure the following tasks are completed before requesting a review:

- [ X ] My code adheres to the style guidelines of this project.
- [ X ] I have run `npm run lint` or the equivalent linting command (npx eslint .).
- [ ] I have added or updated tests (if applicable).
- [ X ] My changes have been tested thoroughly in different browsers/resolutions (if applicable).
- [ ] I have updated the documentation (if applicable).
- [ X ] I have checked that there are no console errors or warnings.
- [ X ] I have verified that the application builds without errors.
- [ X ] I have tested responsiveness for mobile and desktop views (if applicable).

---

## 🚀 Changes Made

- **New Features:**

- > Addition of a new component that works both as a single date picker and a date range picker.

- **Bug Fixes:**
  - [List the bugs fixed.]

- **Refactoring:**
  - [Highlight refactored code, if any.]

- **Other Changes:**
  - [Describe additional changes not covered above.]

---

## 💡 How to Test

Please provide clear instructions on how reviewers can test your changes:

1- Add the `<DatePicker /> `component to the desired location.
2- The component can be used either as a simple date picker or as a date range picker through the allowRangeSelection parameter (`<DatePicker allowRangeSelection />`).
3- The component also requires the date and setDate parameters. If it is used as a date range picker, you must also pass the dateRange parameter, which should receive an object of type DateRange, and a setDateRange.
4- Example of a <DatePicker /> component call:

```
import { DatePicker } from "@/components/ui/datePicker";
import React from "react";
import { DateRange } from "../types/DateRange";

const TestPage = () => {
  const [date, setDate] = React.useState<Date>(new Date());
  const [dateRange, setDateRange] = React.useState<DateRange>();
  
  return (
    <div className="h-full">
      <h1>Página de Teste</h1>
      <p>Esta é uma página de teste para o novo componente.</p>
      <DatePicker
        date={date}
        setDate={setDate} 
        allowRangeSelection
        dateRange={dateRange}
        setDateRange={setDateRange}
      ></DatePicker>
    </div>
  );
};
```

---

## 🤝 Related Issues

List any related issues, pull requests, or discussions:

- #123
- #456

---

## 🔗 Additional Context (optional)

Add any other context or information that might be useful for reviewers:

[Additional notes or links]

---

## 📄 Relevant Documentation (optional)

---

## 📋 Review Guidelines

Please focus on the following while reviewing:

- [ ] Does the code follow the repository's contribution guidelines?
- [ ] Are there any potential bugs or performance issues?
- [ ] Is the UI consistent with the overall design?
- [ ] Are there any typos or grammatical errors in the code or comments?

### CODE REVIEW

**Comment by cryptosalomao** [comment]
Hi @matosGu1lherme thank you for the time invested in this task so far! I still have to spare some time to review it thoroughly and provide you with a detailed feedback. In the mean time, would you care to join our Discord community?

Here's the link:
https://discord.com/invite/TqUN3Nc7DN

**Comment by mjkeaton** [comment]
Hey @matosGu1lherme. Thanks for the contribution :orange_heart: 

Would it be possible to do the following:
- Rebase on `main`
- Create stories ([storybook](https://storybook.js.org/); `npm run storybook`) for new components
- Take into account internationalization (e.g. [here](https://github.com/BitcreditProtocol/E-Bill-frontend/pull/108/files#diff-e84aa990bbc1ddbaee21f4d8dd191d22ac4dccad89aa2b90526686a66ea22436R29) and [here](https://github.com/BitcreditProtocol/E-Bill-frontend/pull/108/files#diff-80d03cb4fede678901f041b87fd9dcff05c5349a742f65577c5ab5f0a90df4a4R15))
- Follow [Figma](https://www.figma.com/design/JUTOkJ4dttgNpShfezegeM/Bitcredit-E-bills?node-id=2625-10709&node-type=frame&t=l05jLpdEyPPe1dLX-0) more closely - it is already looking great, just a little bit of padding, icons, colors, etc.! :pray:

**Comment by matosGu1lherme** [comment]
Hi @mjkeaton, thanks for the feedback! I’ll make the necessary changes and send them over, but I have a few questions before proceeding:

1- Is there an existing library or approach already being used in the project for internationalization, or is there a preferred way to handle it?
2- Regarding the style adjustments, are there specific points you would like me to focus on or change?
3- Lastly, regarding the Vercel bot and the failed build, do I need to do anything about it? Where can I find more information on this issue?
Thanks again! Looking forward to your reply.

**Comment by matosGu1lherme** [comment]
Hi cryptosalomao, no problem, and I will join for sure. Thank you very much for the invitation!

**Comment by mjkeaton** [comment]
> Hi @mjkeaton, thanks for the feedback! I’ll make the necessary changes and send them over, but I have a few questions before proceeding:
> 
> 1- Is there an existing library or approach already being used in the project for internationalization, or is there a preferred way to handle it?

Yes, [`react-intl`](https://formatjs.github.io/).

> 2- Regarding the style adjustments, are there specific points you would like me to focus on or change? 

Try to be as close as possible to Figma ("pixel perfect").



> 3- Lastly, regarding the Vercel bot and the failed build, do I need to do anything about it? Where can I find more information on this issue? 

Regarding the build, your package.json and package-lock.json are out of sync. I think you just need to call `npm install` and commit the changes to `package-lock.json`.

[See the error message](https://github.com/BitcreditProtocol/E-Bill-frontend/actions/runs/12107955419/job/33834997659?pr=108#step:4:7):
```
npm error `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
```

Regarding Vercel, I think deploying to Vercel is disabled for external contributions. Once it is merged, it will be deployed - which will be successful if the build step (above) succeeds.

> Thanks again! Looking forward to your reply.

Thank you! :pray: 

Storybook Stories help a great deal when reviewing! :raised_hands:

**Comment by matosGu1lherme** [comment]
Hey @mjkeaton, it was just the package.json, haha. Thanks for the tip 🙌 I was really puzzled about it. I'll make the other changes you suggested and let you know here once I'm done. Sound good ?

**Comment by matosGu1lherme** [comment]
hi @cryptosalomao, i finished the changes, you can continue with the review

**Comment by matosGu1lherme** [comment]
Hi, @mjkeaton 

Regarding the requirement, I believe so. The component adjusts its behavior based on the allowRangeSelection parameter. If it is set to false, the component works as a single date picker. However, if I misunderstood the requirement, I’m open to modifying it.

As for the dependency, the project started requiring it after I pulled updates from the main branch. I thought it might be related to the merge between my fork and the main branch.

Regarding the layout differences you identified, I’ll update those. Apologies for the delays; the component has become quite large and includes many functionalities. But I’ll keep posting the updates as requested so we can arrive at the best possible version. If you have any suggestions for changes, feel free to let me know.

**Comment by mjkeaton** [comment]
> Hi, @mjkeaton
> 
> Regarding the requirement, I believe so. The component adjusts its behavior based on the allowRangeSelection parameter. If it is set to false, the component works as a single date picker. However, if I misunderstood the requirement, I’m open to modifying it.

Hmm.. but I only see `mode="single"` - Any reason you have not used [mode "range"](https://daypicker.dev/docs/selection-modes#range-mode) when picking start and end date?

> 
> As for the dependency, the project started requiring it after I pulled updates from the main branch. I thought it might be related to the merge between my fork and the main branch.

I'll take care.

> 
> Regarding the layout differences you identified, I’ll update those. Apologies for the delays; the component has become quite large and includes many functionalities. But I’ll keep posting the updates as requested so we can arrive at the best possible version. If you have any suggestions for changes, feel free to let me know.

No, please do not make any changes yet. I am currently deep into the review and have created a follow-up PR with changes you might welcome - if you think they are worthwhile and good improvements.

**Comment by mjkeaton** [comment]
@matosGu1lherme As discussed in Discord: Please look over the changes in https://github.com/BitcreditProtocol/E-Bill-frontend/tree/mjk/108-review and merge them if you are happy with it :pray:

**Comment by mjkeaton** [comment]
LGTM. 

@cryptosalomao There are still some things that need to be adapted when really integrating it into a function form for the first time. But this can be done in a follow-up PR. I'd merge now.

Thanks @matosGu1lherme!

**Review by mjkeaton — APPROVED** [review]

**Pull request merged**
